/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Interfaz;

import DTO.PersonaGeneradaDTO;
import com.toedter.calendar.JDateChooser;
import java.util.ArrayList;
import java.util.Calendar;
import java.util.Date;
import java.util.List;
import javax.swing.DefaultComboBoxModel;
import javax.swing.JOptionPane;
import negocio.PersonaConsulta;



/**
 *
 * @author elimo
 */
public class JFrameBuscar extends javax.swing.JFrame {

    private JDateChooser dateChooserDesde;
    private JDateChooser dateChooserHasta;
    
    public JFrameBuscar() {
        initComponents();
        setLocationRelativeTo(null);
        inicializarSelectores();
        limitarFecha();
        dateChooserHasta.setEnabled(false);
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel3 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        btnBuscar = new javax.swing.JButton();
        txtOtroDate = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        txtCurp = new javax.swing.JTextField();
        btnRegresar = new javax.swing.JButton();
        jLabel11 = new javax.swing.JLabel();
        txtNombrePersona = new javax.swing.JTextField();
        cbxPersona = new javax.swing.JComboBox<>();
        btnSeleccionarPersona = new javax.swing.JButton();
        lblFechaDesde = new javax.swing.JLabel();
        lblFechaHasta = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel3.setBackground(new java.awt.Color(204, 204, 204));
        jPanel3.setFocusCycleRoot(true);
        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel2.setBackground(new java.awt.Color(51, 102, 255));
        jPanel2.setMaximumSize(new java.awt.Dimension(600, 60));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iconos/sonoraLogoImagen.png"))); // NOI18N
        jPanel2.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 94, 40));

        jPanel4.setBackground(new java.awt.Color(51, 204, 255));
        jPanel4.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        jPanel2.add(jPanel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 40, 600, 20));

        jLabel4.setFont(new java.awt.Font("Segoe UI", 1, 20)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Transacciones y mas");
        jPanel2.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 5, -1, -1));

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iconos/fondoImagen.jpeg"))); // NOI18N
        jPanel2.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(94, 0, 506, 40));

        jLabel8.setFont(new java.awt.Font("Segoe UI", 1, 20)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setText("Transacciones y mas");
        jPanel2.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 5, -1, -1));

        jPanel3.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 600, 60));

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setMaximumSize(new java.awt.Dimension(393, 267));
        jPanel1.setMinimumSize(new java.awt.Dimension(393, 267));
        jPanel1.setPreferredSize(new java.awt.Dimension(393, 267));

        btnBuscar.setText("Buscar");
        btnBuscar.setBackground(new java.awt.Color(204, 204, 204));
        btnBuscar.setEnabled(false);
        btnBuscar.setForeground(new java.awt.Color(51, 102, 255));
        btnBuscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBuscarActionPerformed(evt);
            }
        });

        txtOtroDate.setText(">");
        txtOtroDate.setBackground(new java.awt.Color(204, 204, 204));
        txtOtroDate.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        txtOtroDate.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        txtOtroDate.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                txtOtroDateMouseClicked(evt);
            }
        });

        jLabel5.setText("CURP");

        jLabel7.setText("Periodo de transaccion");

        jLabel9.setText("De");

        txtCurp.setBackground(new java.awt.Color(204, 204, 204));
        txtCurp.setDisabledTextColor(new java.awt.Color(0, 0, 0));
        txtCurp.setForeground(new java.awt.Color(255, 255, 255));
        txtCurp.setToolTipText("");
        txtCurp.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtCurpKeyReleased(evt);
            }
        });

        btnRegresar.setText("Regresar");
        btnRegresar.setBackground(new java.awt.Color(204, 204, 204));
        btnRegresar.setForeground(new java.awt.Color(51, 102, 255));
        btnRegresar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRegresarActionPerformed(evt);
            }
        });

        jLabel11.setText("Nombre del dueño");
        jLabel11.setBackground(new java.awt.Color(0, 0, 0));

        txtNombrePersona.setBackground(new java.awt.Color(204, 204, 204));
        txtNombrePersona.setDisabledTextColor(new java.awt.Color(0, 0, 0));
        txtNombrePersona.setForeground(new java.awt.Color(0, 0, 0));
        txtNombrePersona.setToolTipText("");
        txtNombrePersona.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtNombrePersonaKeyReleased(evt);
            }
        });

        cbxPersona.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                cbxPersonaFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                cbxPersonaFocusLost(evt);
            }
        });
        cbxPersona.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbxPersonaActionPerformed(evt);
            }
        });
        cbxPersona.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                cbxPersonaKeyReleased(evt);
            }
        });

        btnSeleccionarPersona.setText("Seleccionar");
        btnSeleccionarPersona.setBackground(new java.awt.Color(204, 204, 204));
        btnSeleccionarPersona.setForeground(new java.awt.Color(51, 102, 255));
        btnSeleccionarPersona.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSeleccionarPersonaActionPerformed(evt);
            }
        });

        jLabel6.setText("hasta");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(jLabel11))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(txtNombrePersona, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(jLabel5))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(txtCurp, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(cbxPersona, javax.swing.GroupLayout.PREFERRED_SIZE, 230, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(10, 10, 10)
                .addComponent(btnSeleccionarPersona, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(jLabel7))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(170, 170, 170)
                .addComponent(jLabel6))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addComponent(lblFechaDesde, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(30, 30, 30)
                .addComponent(txtOtroDate, javax.swing.GroupLayout.PREFERRED_SIZE, 15, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(25, 25, 25)
                .addComponent(lblFechaHasta, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(50, 50, 50)
                .addComponent(btnRegresar, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(55, 55, 55)
                .addComponent(btnBuscar, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(10, 10, 10)
                .addComponent(jLabel11)
                .addGap(4, 4, 4)
                .addComponent(txtNombrePersona, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(jLabel5)
                .addGap(4, 4, 4)
                .addComponent(txtCurp, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(20, 20, 20)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(cbxPersona, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnSeleccionarPersona, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addComponent(jLabel7)
                .addGap(4, 4, 4)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel9)
                    .addComponent(jLabel6))
                .addGap(4, 4, 4)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblFechaDesde, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(5, 5, 5)
                        .addComponent(txtOtroDate, javax.swing.GroupLayout.PREFERRED_SIZE, 15, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(lblFechaHasta, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(10, 10, 10)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnRegresar, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnBuscar, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)))
        );

        jPanel3.add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 70, 400, 267));

        getContentPane().add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 600, 350));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnBuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBuscarActionPerformed
        // TODO add your handling code here:
        if(dateChooserHasta.getCalendar()==null){
            
            JOptionPane.showMessageDialog(this, "No se a seleccionado fecha limite", "ERROR!!!", JOptionPane.ERROR_MESSAGE);
            
        }else if(dateChooserDesde.getCalendar()==null){
            
            JOptionPane.showMessageDialog(this, "No se a seleccionado ninguna fecha inicial", "ERROR!!!", JOptionPane.ERROR_MESSAGE);
            
        }else{
            
            JFrameHistorial historial = new JFrameHistorial((PersonaGeneradaDTO)cbxPersona.getSelectedItem(), dateChooserDesde.getCalendar(), dateChooserHasta.getCalendar());
            historial.setVisible(true);
            this.dispose();
            
            
        }
        

    }//GEN-LAST:event_btnBuscarActionPerformed

    public void inicializarSelectores(){
        
        dateChooserDesde = new JDateChooser();
        dateChooserDesde.setBounds(lblFechaDesde.getBounds());
        dateChooserHasta = new JDateChooser();
        dateChooserHasta.setBounds(lblFechaHasta.getBounds());
        jPanel1.add(dateChooserDesde);
        jPanel1.add(dateChooserHasta);
        
    }
    
    
    
    public void limitarFechaHasta(Calendar fecha){
        
        Calendar fechaMaxima = Calendar.getInstance();
        Date maximo = fechaMaxima.getTime();
        
        Date minimo = fecha.getTime();
        dateChooserHasta.setSelectableDateRange(minimo, maximo);
        
    }
    
    public void limitarFecha(){
        
        Calendar fechaMaxima = Calendar.getInstance();
        fechaMaxima.add(Calendar.DATE, -1);
        Date maximo = fechaMaxima.getTime();
        
        Calendar fechaMinima = Calendar.getInstance();
        fechaMinima.set(Calendar.YEAR, 1900);
        Date minimo = fechaMinima.getTime();
        dateChooserDesde.setSelectableDateRange(minimo, maximo);
        
    }
    
    private void txtNombrePersonaKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtNombrePersonaKeyReleased
        // TODO add your handling code here:
        cargarComboBoxPersona();
        if(cbxPersona.getSelectedItem()== null){

            JOptionPane.showMessageDialog(this, "No hay personas con ese nombre", "ERROR!!", JOptionPane.ERROR_MESSAGE);
            txtNombrePersona.setText("");
            btnBuscar.setEnabled(false);

        }
        
    }//GEN-LAST:event_txtNombrePersonaKeyReleased
    
    
    
    
    public void cargarComboBoxPersona(){
        
        DefaultComboBoxModel modeloComboBox = new DefaultComboBoxModel();
        cbxPersona.setModel(modeloComboBox);
        List<PersonaGeneradaDTO> personas = listaPersonasNombre();
        for (PersonaGeneradaDTO persona : personas) {
            modeloComboBox.addElement(persona);
        }
        
    }
    
    public List<PersonaGeneradaDTO> listaPersonasNombre(){
        
        PersonaConsulta personaConsulta = new PersonaConsulta();
        return personaConsulta.listaPersonasNombre(txtNombrePersona.getText());
        
    }
    
    private void cbxPersonaFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_cbxPersonaFocusGained
        // TODO add your handling code here:

        //        cargarComboBoxVehiculo();
        //        cbxVehiculo.setEnabled(true);
    }//GEN-LAST:event_cbxPersonaFocusGained

    private void cbxPersonaFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_cbxPersonaFocusLost
        // TODO add your handling code here:

        if(listaPersonasNombre()==null){

            JOptionPane.showMessageDialog(this, "No existe ese nombre", "ERROR!!", JOptionPane.ERROR_MESSAGE);
            txtNombrePersona.setText("");

        }
    }//GEN-LAST:event_cbxPersonaFocusLost

    private void cbxPersonaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbxPersonaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cbxPersonaActionPerformed

    private void cbxPersonaKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_cbxPersonaKeyReleased
        // TODO add your handling code here:
    }//GEN-LAST:event_cbxPersonaKeyReleased

    private void btnSeleccionarPersonaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSeleccionarPersonaActionPerformed
        // TODO add your handling code here:

        if(cbxPersona.getSelectedItem()==null){

            JOptionPane.showMessageDialog(this, "No se a seleccionado ninguna persona", "ERROR!!", JOptionPane.ERROR_MESSAGE);

        }else if(btnSeleccionarPersona.getText().equalsIgnoreCase("Seleccionar")){

            btnBuscar.setEnabled(true);
            cbxPersona.setEnabled(false);
            txtCurp.setEnabled(false);
            txtNombrePersona.setEnabled(false);
            btnSeleccionarPersona.setText("Editar");
            
        }else if(btnSeleccionarPersona.getText().equalsIgnoreCase("Editar")){
            
            btnBuscar.setEnabled(false);
            cbxPersona.setEnabled(true);
            txtCurp.setEnabled(true);
            txtNombrePersona.setEnabled(true);
            btnSeleccionarPersona.setText("Seleccionar");
            
        }
    }//GEN-LAST:event_btnSeleccionarPersonaActionPerformed

    private void txtCurpKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtCurpKeyReleased
        // TODO add your handling code here:
        
        cargarComboBoxPersona();
        if(cbxPersona.getSelectedItem()== null){

            JOptionPane.showMessageDialog(this, "No hay personas con ese nombre", "ERROR!!", JOptionPane.ERROR_MESSAGE);
            txtNombrePersona.setText("");
            btnBuscar.setEnabled(false);

        }
        
        List<PersonaGeneradaDTO> listaPersonas = new ArrayList<>();
        for(int i = 0; i < cbxPersona.getItemCount(); i ++){

            listaPersonas.add((PersonaGeneradaDTO)cbxPersona.getSelectedItem());

        }
        cargarComboBoxPersonaCurp();
        if(cbxPersona.getSelectedItem()== null){

        JOptionPane.showMessageDialog(this, "No hay personas con esa curp", "ERROR!!", JOptionPane.ERROR_MESSAGE);
        txtCurp.setText("");
        btnBuscar.setEnabled(false);
        cargarComboBoxPersona();

        }
        
        
    }//GEN-LAST:event_txtCurpKeyReleased

    private void btnRegresarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRegresarActionPerformed
        // TODO add your handling code here:

        JFrameInicio inicio = new JFrameInicio();
        inicio.setVisible(true);
        this.dispose();

    }//GEN-LAST:event_btnRegresarActionPerformed

    private void txtOtroDateMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtOtroDateMouseClicked
        // TODO add your handling code here:
        if(dateChooserDesde.getCalendar()==null){
            
            JOptionPane.showMessageDialog(this, "No a seleccionado ninguna fecha", "ERROR!!!", JOptionPane.ERROR_MESSAGE);
            
        }else{
            
            if(txtOtroDate.getText().equalsIgnoreCase(">")){
            
                txtOtroDate.setText("<");
                dateChooserDesde.setEnabled(false);
                dateChooserHasta.setEnabled(true);
                Calendar fecha = dateChooserDesde.getCalendar();
                fecha.add(Calendar.DATE, 1);
                limitarFechaHasta(fecha);
            
            }else if(txtOtroDate.getText().equalsIgnoreCase("<")){

                txtOtroDate.setText(">");
                dateChooserDesde.setEnabled(true);
                dateChooserHasta.setEnabled(false);

            }

        }
        
        
    }//GEN-LAST:event_txtOtroDateMouseClicked

    public void cargarComboBoxPersonaCurp(){
        
        DefaultComboBoxModel modeloComboBox = new DefaultComboBoxModel();
        cbxPersona.setModel(modeloComboBox);
        List<PersonaGeneradaDTO> listaPersonasCurp = listaPersonasNombreCurp();
        for (PersonaGeneradaDTO persona : listaPersonasCurp) {
            modeloComboBox.addElement(persona);
        }
        
    }
    
    public List<PersonaGeneradaDTO> listaPersonasNombreCurp(){
        
        PersonaConsulta personaConsulta = new PersonaConsulta();
        return personaConsulta.listaPersonasNombreCurp(txtNombrePersona.getText(), txtCurp.getText());
        
    }
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBuscar;
    private javax.swing.JButton btnRegresar;
    private javax.swing.JButton btnSeleccionarPersona;
    private javax.swing.JComboBox<String> cbxPersona;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JLabel lblFechaDesde;
    private javax.swing.JLabel lblFechaHasta;
    private javax.swing.JTextField txtCurp;
    private javax.swing.JTextField txtNombrePersona;
    private javax.swing.JLabel txtOtroDate;
    // End of variables declaration//GEN-END:variables
}
