package Interfaz;

import DTO.PersonaGeneradaDTO;
import DTO.TramiteDTO;
import java.util.ArrayList;
import java.util.Calendar;
import java.util.List;
import javax.swing.table.DefaultTableModel;
import negocio.TramiteConsulta;


/**
 *
 * @author Amós Helí Olguín Quiróz
 */
public class JFrameHistorial extends javax.swing.JFrame {

    List<TramiteDTO> listaTramites;
    
    PersonaGeneradaDTO personaGeneradaDTO;
    Calendar fechaDesde;
    Calendar fechaHasta;
    private String licencia = "LicenciaEntidad";
    private String placa = "PlacaEntidad";
    
    /**
     * Creates new form JFrameHistorial
     */
    public JFrameHistorial(PersonaGeneradaDTO personaGeneradaDTO, Calendar fechaDesde, Calendar fechaHasta) {
        initComponents();
        setLocationRelativeTo(null);
        
        this.fechaDesde = fechaDesde;
        this.fechaHasta = fechaHasta;
        this.personaGeneradaDTO = personaGeneradaDTO;
        listaTramites = new ArrayList<>();
        lblNombre.setText(personaGeneradaDTO.getNombres());
        tblTramites.setModel(convertirModel(0));
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel3 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        btnTodos = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblTramites = new javax.swing.JTable();
        btnRegresar = new javax.swing.JButton();
        btnLicencias = new javax.swing.JButton();
        btnPlacas = new javax.swing.JButton();
        lblNombre = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel3.setBackground(new java.awt.Color(204, 204, 204));
        jPanel3.setFocusCycleRoot(true);
        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel2.setBackground(new java.awt.Color(51, 102, 255));
        jPanel2.setMaximumSize(new java.awt.Dimension(600, 60));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iconos/sonoraLogoImagen.png"))); // NOI18N
        jPanel2.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 94, 40));

        jPanel4.setBackground(new java.awt.Color(51, 204, 255));
        jPanel4.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        jPanel2.add(jPanel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 40, 600, 20));

        jLabel4.setFont(new java.awt.Font("Segoe UI", 1, 20)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Transacciones y mas");
        jPanel2.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 5, -1, -1));

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iconos/fondoImagen.jpeg"))); // NOI18N
        jPanel2.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(94, 0, 506, 40));

        jLabel8.setFont(new java.awt.Font("Segoe UI", 1, 20)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setText("Transacciones y mas");
        jPanel2.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 5, -1, -1));

        jPanel3.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 600, 60));

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setMaximumSize(new java.awt.Dimension(393, 267));
        jPanel1.setMinimumSize(new java.awt.Dimension(393, 267));
        jPanel1.setPreferredSize(new java.awt.Dimension(393, 267));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnTodos.setBackground(new java.awt.Color(204, 204, 204));
        btnTodos.setForeground(new java.awt.Color(51, 102, 255));
        btnTodos.setText("Todos");
        btnTodos.setEnabled(false);
        btnTodos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTodosActionPerformed(evt);
            }
        });
        jPanel1.add(btnTodos, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 40, 105, 25));

        tblTramites.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "Tipo", "Fecha tramite", "Fecha vencimiento", "Costo", "Estado"
            }
        ));
        tblTramites.setToolTipText("");
        tblTramites.setGridColor(new java.awt.Color(153, 153, 153));
        tblTramites.setSelectionBackground(new java.awt.Color(255, 255, 255));
        jScrollPane1.setViewportView(tblTramites);

        jPanel1.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 80, 380, 130));

        btnRegresar.setBackground(new java.awt.Color(204, 204, 204));
        btnRegresar.setForeground(new java.awt.Color(51, 102, 255));
        btnRegresar.setText("Regresar");
        btnRegresar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRegresarActionPerformed(evt);
            }
        });
        jPanel1.add(btnRegresar, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 230, 105, 25));

        btnLicencias.setBackground(new java.awt.Color(204, 204, 204));
        btnLicencias.setForeground(new java.awt.Color(51, 102, 255));
        btnLicencias.setText("Licencias");
        btnLicencias.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLicenciasActionPerformed(evt);
            }
        });
        jPanel1.add(btnLicencias, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 40, 105, 25));

        btnPlacas.setBackground(new java.awt.Color(204, 204, 204));
        btnPlacas.setForeground(new java.awt.Color(51, 102, 255));
        btnPlacas.setText("Placas");
        btnPlacas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPlacasActionPerformed(evt);
            }
        });
        jPanel1.add(btnPlacas, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 40, 105, 25));
        jPanel1.add(lblNombre, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 10, 230, 20));

        jPanel3.add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 70, 393, 267));

        getContentPane().add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 600, 350));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    public void inicializarLista(){
        
        TramiteConsulta tramiteConsulta = new TramiteConsulta();
        listaTramites = tramiteConsulta.listaTramitesPersona(personaGeneradaDTO, fechaHasta, fechaDesde);
    }
    
    public void inicializarListaTipo(String tipo){
        
        TramiteConsulta tramiteConsulta = new TramiteConsulta();
        listaTramites = tramiteConsulta.listaTramitePersonaTipo(personaGeneradaDTO, tipo, fechaHasta, fechaDesde);
    }
    
    private void btnTodosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTodosActionPerformed
        // TODO add your handling code here:
        
        tblTramites.setModel(convertirModel(0));
        btnTodos.setEnabled(false);
        btnPlacas.setEnabled(true);
        btnLicencias.setEnabled(true);
        
    }//GEN-LAST:event_btnTodosActionPerformed

    private void btnRegresarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRegresarActionPerformed
        // TODO add your handling code here:
        
        JFrameBuscar buscar = new JFrameBuscar();
        buscar.setVisible(true);
        this.dispose();
        
    }//GEN-LAST:event_btnRegresarActionPerformed

    private void btnLicenciasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLicenciasActionPerformed
        // TODO add your handling code here:
        tblTramites.setModel(convertirModel(1));
        btnTodos.setEnabled(true);
        btnPlacas.setEnabled(true);
        btnLicencias.setEnabled(false);
        
    }//GEN-LAST:event_btnLicenciasActionPerformed

    private void btnPlacasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPlacasActionPerformed
        // TODO add your handling code here:
        
        tblTramites.setModel(convertirModel(2));
        btnTodos.setEnabled(true);
        btnPlacas.setEnabled(false);
        btnLicencias.setEnabled(true);
        
    }//GEN-LAST:event_btnPlacasActionPerformed

    
    
    public DefaultTableModel convertirModel(int tipo){
        String estado;
        String fechaVencimiento = "";
        String descripcionTipo = "";
            
        DefaultTableModel modelo = new DefaultTableModel();
        modelo.addColumn("Tipo");
        modelo.addColumn("Fecha tramite");
        modelo.addColumn("Fecha vencimiento");
        modelo.addColumn("Costo");
        modelo.addColumn("Estado");
        modelo.setRowCount(0);
        if(tipo == 0){
            
            inicializarLista();
            
        }else if(tipo == 1){
            
            inicializarListaTipo("LicenciaEntidad");
            descripcionTipo = "Licencia";
            
        }else if(tipo == 2){
                    
            inicializarListaTipo("PlacaEntidad");
            descripcionTipo = "Placa";
        }
        for (TramiteDTO tramite: listaTramites) {
          
            if(tipo==0){
                
                descripcionTipo = saberTipo(tramite);
                
            }
            estado = saberEstado(tramite);
            fechaVencimiento = saberFechaVencimiento(tramite);
            String fechaModelada = modelarFecha(tramite);
            modelo.addRow(new Object[]{
                descripcionTipo,
                fechaModelada,
                fechaVencimiento,
                "$"+tramite.getCosto(),
                estado
            });
        }
        
        return modelo;
        
    }
    
    public String modelarFecha(TramiteDTO tramite){
        
        return tramite.getFechaTramite().get(Calendar.DAY_OF_MONTH) + "/" + (tramite.getFechaTramite().get(Calendar.MONTH)+1) + "/" + tramite.getFechaTramite().get(Calendar.YEAR);
                
        
    }
    
    public String saberTipo(TramiteDTO tramite){
        
        if(tramite.getTipo().equalsIgnoreCase("LicenciaEntidad")){
                    
            return "Licencia";

        }else{

            return "Placa";

        }
        
    }
    
    public String saberEstado(TramiteDTO tramite){
        
        if(tramite.getEstado()==0){
                
            return "Inactivo";

        }else{

            return "Activo";

        }
        
    }
    
    public String saberFechaVencimiento(TramiteDTO tramite){
        
        TramiteConsulta tramiteConsulta = new TramiteConsulta();
        
        if(tramite.getTipo().equalsIgnoreCase("LicenciaEntidad")){
                
            return tramite.getFechaTramite().get(Calendar.DAY_OF_MONTH) + "/" + (tramite.getFechaTramite().get(Calendar.MONTH)+1) + "/" + (tramite.getFechaTramite().get(Calendar.YEAR) + tramiteConsulta.vigenciaLicencia(tramite));

        }
        if(tramite.getTipo().equalsIgnoreCase("PlacaEntidad")){

            return tramite.getFechaTramite().get(Calendar.DAY_OF_MONTH) + "/" + (tramite.getFechaTramite().get(Calendar.MONTH)+1) + "/" + (tramite.getFechaTramite().get(Calendar.YEAR) + 1);

        }
        return null;
        
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnLicencias;
    private javax.swing.JButton btnPlacas;
    private javax.swing.JButton btnRegresar;
    private javax.swing.JButton btnTodos;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblNombre;
    private javax.swing.JTable tblTramites;
    // End of variables declaration//GEN-END:variables
}
